### ISSUE TITLE
Please update to 1.15.2？

### ISSUE THREAD

**Issue by wdog5** [gudenau/minecraft-fcm#1]

**Comment by wdog5** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: net/gudenau/minecraft/fcm/Transformer

	at org.spongepowered.asm.mixin.transformer.MixinTransformerProxy/884603232.transformClassBytes(Unknown Source)

	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)

	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)

	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

	at net.fabricmc.fabric.impl.client.indigo.IndigoMixinConfigPlugin.loadIfNeeded(IndigoMixinConfigPlugin.java:45)

	at net.fabricmc.fabric.impl.client.indigo.IndigoMixinConfigPlugin.shouldApplyIndigo(IndigoMixinConfigPlugin.java:60)

	at net.fabricmc.fabric.impl.client.indigo.IndigoMixinConfigPlugin.shouldApplyMixin(IndigoMixinConfigPlugin.java:79)

	at org.spongepowered.asm.mixin.transformer.PluginHandle.shouldApplyMixin(PluginHandle.java:132)

	at org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:978)

	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:943)

	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:872)

	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715)

	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:652)

	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515)

	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440)

	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416)

	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)

	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)

	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)

	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)

	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)

	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190)

	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)

	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

Caused by: java.lang.ClassNotFoundException: net.gudenau.minecraft.fcm.Transformer

	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)

	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

	... 27 more
